# Generated by Django 5.2.1 on 2025-05-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_iprrequest_projectrequest_delete_studentrequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrequest',
            old_name='student_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='projectrequest',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projectrequest',
            old_name='project_interested',
            new_name='project_title',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='motivation',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
