# Generated by Django 5.2.1 on 2025-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_project_title_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iprrequest',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='iprrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='iprrequest',
            name='ipr_title',
        ),
        migrations.RemoveField(
            model_name='iprrequest',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='iprrequest',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='iprrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='iprrequest',
            name='invention_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iprrequest',
            name='patent_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iprrequest',
            name='previous_patents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
