# Generated by Django 5.2.1 on 2025-05-27 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_student_name_iprrequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iprrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 27, 20, 57, 15, 998523)),
            preserve_default=False,
        ),
    ]
