# Generated by Django 5.2.1 on 2025-05-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_leader_email_projectrequest_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrequest',
            old_name='email',
            new_name='mentor_email',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='summary',
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='acadamic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='domain_of_project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='grant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='mentor_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='mentor_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='no_of_member',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='project_completion_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
