# Generated by Django 5.2.1 on 2025-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_email_projectrequest_mentor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
