# Generated by Django 5.2.1 on 2025-05-30 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_projectrequest_leader_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
