# Generated by Django 5.2.1 on 2025-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projectrequest_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
