# Generated by Django 5.2.1 on 2025-07-07 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_email_iprrequest_comentor_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPRApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_title', models.CharField(default='Untitled Invention', max_length=255)),
                ('patent_description', models.TextField(default='No patent description provided.')),
                ('num_team_members', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('approved_modification', 'Approved with Modification'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Person', max_length=255)),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
                ('enrollment_id', models.CharField(blank=True, default='', max_length=100)),
                ('semester', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('school', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('college', 'College')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
                ('team_size', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('approved_modification', 'Approved with Modification'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('approved_grant_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('co_mentor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_co_mentor', to='app.persondetails')),
                ('members', models.ManyToManyField(blank=True, related_name='project_team_members', to='app.persondetails')),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_mentor', to='app.persondetails')),
            ],
        ),
        migrations.DeleteModel(
            name='IPRRequest',
        ),
        migrations.RemoveField(
            model_name='project',
            name='acadamic_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='domain_of_project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='grant',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_enrollment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader_school',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member1_department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member1_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member1_enrollment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member1_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member1_phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member1_school',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member2_department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member2_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member2_enrollment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member2_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member2_phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member2_school',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member3_department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member3_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member3_enrollment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member3_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member3_phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member3_school',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member4_department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member4_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member4_enrollment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member4_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member4_phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member4_school',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor_designation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor_phone',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mentor_school',
        ),
        migrations.RemoveField(
            model_name='project',
            name='no_of_member',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_completion_time',
        ),
        migrations.AddField(
            model_name='project',
            name='approved_grant_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='broad_area',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='driving_question',
            field=models.TextField(default='No driving question provided.'),
        ),
        migrations.AddField(
            model_name='project',
            name='early_adopters',
            field=models.TextField(default='No early adopters specified.'),
        ),
        migrations.AddField(
            model_name='project',
            name='existing_alternatives',
            field=models.TextField(default='No existing alternatives provided.'),
        ),
        migrations.AddField(
            model_name='project',
            name='financial_consumables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='financial_mentoring',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='financial_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='has_received_grant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='ipr_potential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='major_problems',
            field=models.TextField(default='No major problems provided.'),
        ),
        migrations.AddField(
            model_name='project',
            name='proposed_solution',
            field=models.TextField(default='No proposed solution provided.'),
        ),
        migrations.AddField(
            model_name='project',
            name='startup_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='sustainability_plan',
            field=models.TextField(default='No sustainability plan provided.'),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.TextField(default='No timeline specified.'),
        ),
        migrations.AddField(
            model_name='project',
            name='unique_value_proposition',
            field=models.TextField(default='No unique value proposition provided.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=255),
        ),
        migrations.AddField(
            model_name='iprapplication',
            name='co_mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipr_co_mentor', to='app.persondetails'),
        ),
        migrations.AddField(
            model_name='iprapplication',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipr_leader', to='app.persondetails'),
        ),
        migrations.AddField(
            model_name='iprapplication',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='ipr_team_members', to='app.persondetails'),
        ),
        migrations.AddField(
            model_name='iprapplication',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipr_mentor', to='app.persondetails'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='team_leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_team_leader', to='app.persondetails'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjectRequest',
        ),
    ]
