# Generated by Django 5.2.1 on 2025-07-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_iprapplication_persondetails_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
    ]
