# Generated by Django 5.2.1 on 2025-07-07 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_projectapplication_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='broad_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='driving_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='early_adopters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='existing_alternatives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='financial_consumables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='financial_mentoring',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='financial_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='ipr_potential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='major_problems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='project_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='proposed_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='startup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='sustainability_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='timeline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='unique_value_proposition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='approved_grant_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='co_mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_mentor', to='app.persondetails'),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='members',
            field=models.ManyToManyField(related_name='members', to='app.persondetails'),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='app.persondetails'),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='team_leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='app.persondetails'),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='team_size',
            field=models.IntegerField(),
        ),
    ]
