# Generated by Django 5.2.1 on 2025-07-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_utilizationcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='project_photos/group/'),
        ),
        migrations.AddField(
            model_name='project',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='project_photos/product/'),
        ),
    ]
