# Generated by Django 5.2.1 on 2025-08-03 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_project_group_photo_project_product_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_of_utilization', models.FileField(upload_to='bills/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_records', to='app.project')),
            ],
        ),
        migrations.DeleteModel(
            name='UtilizationCertificate',
        ),
    ]
